# Generated by Django 4.0.4 on 2022-04-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('LastName', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('corporation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['firstName', 'LastName', 'email', 'corporation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('taskResume', models.CharField(blank=True, max_length=200, null=True)),
                ('creationDate', models.DateField(auto_now_add=True, null=True)),
                ('checkDate', models.DateField(blank=True, null=True)),
                ('finishTask', models.BooleanField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number', 'taskResume', 'creationDate', 'checkDate', 'finishTask'],
            },
        ),
    ]
