# Generated by Django 4.0.4 on 2022-04-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
