# Generated by Django 4.0.4 on 2022-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['checkDate']},
        ),
        migrations.AlterField(
            model_name='tache',
            name='checkDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='creationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tache',
            name='taskResume',
            field=models.CharField(max_length=200),
        ),
    ]
