# Generated by Django 4.0.4 on 2022-04-29 17:57

from django.db import migrations, models
import toDo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0003_alter_tache_options_alter_tache_checkdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='checkDate',
            field=models.DateField(validators=[toDo_app.models.validate_checkDate]),
        ),
    ]
