# Generated by Django 4.0.4 on 2022-04-29 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import toDo_app.models
#validators=[toDo_app.models.validate_checkDate]

class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0004_alter_tache_checkdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='checkDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 18, 7, 50, 346310, tzinfo=utc)),
        ),
    ]
