# Generated by Django 4.0.4 on 2022-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0006_user_alter_tache_checkdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
