# Generated by Django 4.0.4 on 2022-05-07 07:19

import datetime
from django.db import migrations, models
import toDo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='checkDate',
            field=models.DateField(default=datetime.date(2022, 5, 7), validators=[toDo_app.models.validate_checkDate]),
        ),
    ]
