# Generated by Django 4.0.4 on 2022-05-08 13:29

import datetime
from django.db import migrations, models
import toDo_app.models

#validators=[toDo_app.models.finishTask] // validators=[toDo_app.models.validate_checkDate]
class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0010_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='checkDate',
            field=models.DateField(default=datetime.date(2022, 5, 8)),
        ),
        migrations.AlterField(
            model_name='tache',
            name='finishTask',
            field=models.BooleanField(blank=True, null=True )
        ),
    ]
